In [1]:
%matplotlib notebook
import numpy as np
import matplotlib.pylab as plt
import os

import lsst.daf.persistence as dafPersist
import lsst.afw.display as afwDisplay

afwDisplay.setDefaultBackend("matplotlib")

In [4]:
# Let's pull over the catalogs for 
scratch_dir = '/Users/yoachim/Scratch/Stack_Learn'
full_path = os.path.join(scratch_dir, 'DATA/rerun/processCcdOutputs')
# The illustrious Butler
butler = dafPersist.Butler(inputs=full_path)
full_path = os.path.join(scratch_dir, 'DATA/rerun/jointOut')
joint_butler = dafPersist.Butler(inputs=full_path)

In [56]:
# I don't think I know what the jointcal outputs, or how to get the butler to tell me what it has?
# If I query metadata, I think my joint_butler is going back up to find the old calexp, etc?


Help on method queryMetadata in module lsst.daf.persistence.butler:

queryMetadata(datasetType, format, dataId={}, **rest) method of lsst.daf.persistence.butler.Butler instance
    Returns the valid values for one or more keys when given a partial
    input collection data id.
    
    Parameters
    ----------
    datasetType - string
        The type of dataset to inquire about.
    format - str, tuple
        Key or tuple of keys to be returned.
    dataId - DataId, dict
        The partial data id.
    **rest -
        Keyword arguments for the partial data id.
    
    Returns
    -------
    A list of valid values or tuples of valid values as specified by the
    format.



In [58]:
joint_butler.queryMetadata('calexp', ['visit', 'ccd'])

[(903334, 16),
 (903334, 22),
 (903334, 23),
 (903334, 100),
 (903336, 17),
 (903336, 24),
 (903338, 18),
 (903338, 25),
 (903342, 4),
 (903342, 10),
 (903342, 100),
 (903344, 0),
 (903344, 5),
 (903344, 11),
 (903346, 1),
 (903346, 6),
 (903346, 12),
 (903986, 16),
 (903986, 22),
 (903986, 23),
 (903986, 100),
 (903988, 16),
 (903988, 17),
 (903988, 23),
 (903988, 24),
 (903990, 18),
 (903990, 25),
 (904010, 4),
 (904010, 10),
 (904010, 100),
 (904014, 1),
 (904014, 6),
 (904014, 12)]

In [27]:
src = butler.get('src', dataId={'filter': 'HSC-R', 'visit': 903334, 'ccd': 23})

In [48]:
orig_wcs = butler.get('wcs', dataId={'filter': 'HSC-R', 'visit': 903334, 'ccd': 23})

RuntimeError: Cannot look up skymap key 'tract'; it must be explicitly included in the data ID

In [28]:
src

<class 'lsst.afw.table.source.source.SourceCatalog'>
        id            coord_ra   ... calib_photometry_reserved
                        rad      ...                          
------------------ ------------- ... -------------------------
775958096257220609 5.59982919245 ...                     False
775958096257220610 5.59981642684 ...                     False
775958096257220611 5.59981123581 ...                     False
775958096257220612 5.59979486411 ...                     False
775958096257220613 5.59979170649 ...                     False
775958096257220614 5.59979790083 ...                     False
775958096257220615 5.59980359416 ...                     False
775958096257220616 5.59979238037 ...                     False
775958096257220617 5.59979035126 ...                     False
775958096257220618 5.59979814883 ...                     False
               ...           ... ...                       ...
775958096257221748 5.59660762685 ...                     False
77

In [34]:
src['coord_ra']

array([ 5.59982919,  5.59981643,  5.59981124, ...,  5.59659622,
        5.59657621,  5.59658344])

In [45]:
# 
joint_butler.queryMetadata('wcs', ['visit', 'ccd'])

[(903334, 16),
 (903334, 22),
 (903334, 23),
 (903334, 100),
 (903336, 17),
 (903336, 24),
 (903338, 18),
 (903338, 25),
 (903342, 4),
 (903342, 10),
 (903342, 100),
 (903344, 0),
 (903344, 5),
 (903344, 11),
 (903346, 1),
 (903346, 6),
 (903346, 12),
 (903986, 16),
 (903986, 22),
 (903986, 23),
 (903986, 100),
 (903988, 16),
 (903988, 17),
 (903988, 23),
 (903988, 24),
 (903990, 18),
 (903990, 25),
 (904010, 4),
 (904010, 10),
 (904010, 100),
 (904014, 1),
 (904014, 6),
 (904014, 12)]

In [35]:
joint_src = joint_butler.get('src', dataId={'filter': 'HSC-R', 'visit': 903334, 'ccd': 23})

In [ ]:
# Maybe I have to use afwTable.matchRaDec to 

In [46]:
joint_wcs = joint_butler.get('wcs', dataId={'visit':903334, 'ccd': 23})

RuntimeError: Cannot look up skymap key 'tract'; it must be explicitly included in the data ID

In [47]:
wcs = butler.get('wcs', dataId={'visit':903334, 'ccd': 23})

RuntimeError: Cannot look up skymap key 'tract'; it must be explicitly included in the data ID

In [49]:
# OK, I have no idea how to get at the newly fitted wcs objects. Looks like I got the old ones from the calexp.

In [54]:
src.getX(), src.getY()

(array([   18.        ,   618.        ,  1169.        , ...,  1315.42253744,
         1302.        ,  1294.        ]),
 array([    7.        ,    12.        ,     7.        , ...,  4123.57048631,
         4149.        ,  4140.        ]))