In [1]:
import numpy as np
import itertools

In [2]:
numbers = range(1,9)
perms = np.array(list(itertools.permutations(numbers)))

In [3]:
# Constraints. Index from upper-right, ot the left, down, to the right
c1 = np.sum(perms[:, [0,1,2]], axis=1)
c2 = np.sum(perms[:, [2, 3, 4, 5]], axis=1)
c3 = np.sum(perms[:, [5,6,7]], axis=1)

In [4]:
solutions = np.where( (c1 == 15) & (c2 == 15) & (c3 == 15))[0]

In [5]:
solutions

array([ 4806,  4807,  4848,  4849,  9132,  9133,  9192,  9193, 19688,
       19689, 19730, 19731, 24032, 24033, 24056, 24057, 31452, 31453,
       31512, 31513, 33392, 33393, 33416, 33417, 35766, 35767, 35808,
       35809, 37688, 37689, 37730, 37731])

In [6]:
perms[solutions[0], :]

array([1, 8, 6, 2, 4, 3, 5, 7])

In [7]:
perms[solutions[10], :]

array([4, 8, 3, 5, 1, 6, 2, 7])